SPK_NAME = byobu
SPK_VERS = 1.1
SPK_REV = 00
SPK_ICON = src/terminal.jpg

DEPENDS = cross/$(SPK_NAME) cross/screen

MAINTAINER = Peter_Nearing
DESCRIPTION = "Byobu is a GPLv3 open source text-based window manager and terminal multiplexer."
DESCRIPTION_FRE = "Byobu est un gestionnaire de fenêtres texte open source GPLv3 et un multiplexeur de terminal."
DESCRIPTION_SPN = "Byobu es un gestor de ventanas basado en texto de código abierto GPLv3 y multiplexor de terminales."

STARTABLE = no
DISPLAY_NAME = Byobu
CHANGELOG = "Initial build."

HOMEPAGE = https://byobu.org
LICENSE  = GPLv3

SPK_COMMANDS = bin/byobu bin/byobu-config bin/byobu-ctrl-a bin/byobu-disable bin/byobu-disable-prompt bin/byobu-enable bin/byobu-enable-prompt bin/byobu-export bin/byobu-janitor bin/byobu-keybindings bin/byobu-launch bin/byobu-launcher bin/byobu-launcher-install bin/byobu-launcher-uninstall bin/byobu-layout bin/byobu-prompt bin/byobu-quiet bin/byobu-reconnect-sockets bin/byobu-screen bin/byobu-select-backend bin/byobu-select-profile bin/byobu-select-session bin/byobu-shell bin/byobu-silent bin/byobu-status bin/byobu-status-detail bin/byobu-tmux bin/byobu-ugraph bin/byobu-ulevel bin/col1 bin/ctail bin/manifest bin/purge-old-kernels bin/vigpg bin/wifi-status

SPK_USR_LOCAL_LINKS  = bin:bin/byobu
SPK_USR_LOCAL_LINKS += bin:bin/byobu-config
SPK_USR_LOCAL_LINKS += bin:bin/byobu-ctrl-a
SPK_USR_LOCAL_LINKS += bin:bin/byobu-disable
SPK_USR_LOCAL_LINKS += bin:bin/byobu-disable-prompt
SPK_USR_LOCAL_LINKS += bin:bin/byobu-enable
SPK_USR_LOCAL_LINKS += bin:bin/byobu-enable-prompt
SPK_USR_LOCAL_LINKS += bin:bin/byobu-export
SPK_USR_LOCAL_LINKS += bin:bin/byobu-janitor
SPK_USR_LOCAL_LINKS += bin:bin/byobu-keybindings
SPK_USR_LOCAL_LINKS += bin:bin/byobu-launch
SPK_USR_LOCAL_LINKS += bin:bin/byobu-launcher
SPK_USR_LOCAL_LINKS += bin:bin/byobu-launcher-install
SPK_USR_LOCAL_LINKS += bin:bin/byobu-launcher-uninstall
SPK_USR_LOCAL_LINKS += bin:bin/byobu-layout
SPK_USR_LOCAL_LINKS += bin:bin/byobu-prompt
SPK_USR_LOCAL_LINKS += bin:bin/byobu-quiet
SPK_USR_LOCAL_LINKS += bin:bin/byobu-reconnect-sockets
SPK_USR_LOCAL_LINKS += bin:bin/byobu-screen
SPK_USR_LOCAL_LINKS += bin:bin/byobu-select-backend
SPK_USR_LOCAL_LINKS += bin:bin/byobu-select-profile
SPK_USR_LOCAL_LINKS += bin:bin/byobu-select-session
SPK_USR_LOCAL_LINKS += bin:bin/byobu-shell
SPK_USR_LOCAL_LINKS += bin:bin/byobu-silent
SPK_USR_LOCAL_LINKS += bin:bin/byobu-status
SPK_USR_LOCAL_LINKS += bin:bin/byobu-status-detail
SPK_USR_LOCAL_LINKS += bin:bin/byobu-tmux
SPK_USR_LOCAL_LINKS += bin:bin/byobu-ugraph
SPK_USR_LOCAL_LINKS += bin:bin/byobu-ulevel
SPK_USR_LOCAL_LINKS += bin:bin/col1
SPK_USR_LOCAL_LINKS += bin:bin/ctail
SPK_USR_LOCAL_LINKS += bin:bin/manifest
SPK_USR_LOCAL_LINKS += bin:bin/purge-old-kernels
SPK_USR_LOCAL_LINKS += bin:bin/vigpg
SPK_USR_LOCAL_LINKS += bin:bin/wifi-status

include ../../mk/spksrc.spk.mk

